### ISSUE TITLE
run-crash for newbie

### ISSUE THREAD

**Issue by tedzyc** [8tory/SimpleWeibo#5]
Edit: 
Latest comment: find the point: if i run on emulator on android-platform-22, this app will NOT crash
搞清楚了問題，編譯好的工程在5.1.1(API22)的模擬器上運行就不會crash
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Hello, if I run lastest built apk, it will crash, and logcat is:
"java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.simple.app.MainActivity" on path: DexPathList[[zip file "/data/app/com.sina.weibo.sdk.demo-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.sina.weibo.sdk.demo-1, /vendor/lib, /system/lib]]"
我是用android-studio1.3構建的，運行的手機是5.0以下的。大陸網絡環境不好，我也不知道依賴包是否全部都已下載，反正提示build succesful, 可是運行就出這個錯。
小白級的問題，望大神指點！

我下載了demo-apk看了，結果看不了微博詳情頁，不知道最新版本是否可以看詳情，如果方便請發布壹個最新的demo-apk

**Comment by yongjhih** [comment]
How about this: https://github.com/8tory/SimpleWeibo/releases/download/1.0.0/simpleweibo-app-debug.apk

**Comment by tedzyc** [comment]
i have already installed that 1.0.0-apk, it works on pre-Lollipop device, but it can't show weibo-list-item's detail, seem show page like 'cheesesquare'

**Comment by yongjhih** [comment]
It's ok. Because, we didn't complete that detail page.

**Comment by yongjhih** [comment]
Chat: https://gitter.im/8tory/SimpleWeibo

**Comment by tedzyc** [comment]
Thanks for the info and patience. 
Currently I may have no time spent on this problem, but I will try when I am free.

**Comment by tedzyc** [comment]
Latest comment: find the point: if i run on emulator on android-platform-22, this app will NOT crash
搞清楚了問題，編譯好的工程在5.1.1(API22)的模擬器上運行就不會crash

**Comment by yongjhih** [comment]
:+1:
